# application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onboarding
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: onboarding
    password: onboarding
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect	# 이 부분 주의!
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        dialect.storage_engine: innodb
    hibernate:
      ddl-auto: create	# 실서버에서는 validate로 설정해야 한다!